apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-runner-token
  namespace: gitlab
spec:
  backendType: systemManager
  data:
    - key: /k8s-gitlab-runner/token/test
      name: runner-registration-token